### ISSUE TITLE
Question: What is an example of a 'Key'?

### ISSUE THREAD

**Issue by stevepm** [fzakaria/HypeScript#16]
Just trying to figure out from looking at the Hypem.com page what an example of the key is. For this page (http://hypem.com/track/28p60/Soft+Power+-+To+The+Shaggerston), I assume the ID is '28p60'. Is the key the title?

**Comment by fzakaria** [comment]
you can't see the key from the URL.
You have to inspect the javascript object that stores them (if i remember correctly)

**Comment by fzakaria** [comment]
I guess it was parsed from the HTML. You can cross reference with how I do it on the Javascript/Chrome extension as well
