### ISSUE TITLE
Hypem redirect breaking script - lazy fix

### ISSUE THREAD

**Issue by pea-arthur** [fzakaria/HypeScript#26]
I tried the script today after a long hiatus and it failed "0 songs parsed". Fetching http://hypem.com/popular returns a redirect:
<script type="text/javascript">load_url('https://hypem.com/popular/1?ax=1&ts=xxxx');</script>  where xxxx is a timestamp? 

The URL needs to be extracted and the script run again in order to function.

AREA_TO_SCRAPE=''
HYPEM_URL= 'https://hypem.com/popular/1?ax=1&ts=xxxx'

Here's a lazy way to strip out the redirect and re-download the desired file:

`            html2, cookie = self.get_html_file(page_url)
            print html2
            html2 = html2.strip("""<script type="text/javascript">load_url('""")
            print html2
            html2 = html2.strip("""');""")
            print html2
            html, cookie = self.get_html_file(html2)`

I'm sure there's a more elegant solution.

**Comment by djschny** [comment]
Switching to https by default did the trick for me - https://github.com/fzakaria/HypeScript/pull/27

**Comment by fzakaria** [comment]
Closing. Changed to HTTPS.
